[ main ]
plugins = [ "bilibili", "github" ,"oseddl", "invite", "hust_eat", "hust_mirror" ]
adapter = "onebot11"

# 供插件使用的配置
[ oseddl ]
oseddl_github_token = ""
oseddl_base_url = "https://gitee.com/YeyingXingchen/open-source-deadlines/raw/main/data"

# oseddl_base_url = "https://github.com/hust-open-atom-club/open-source-deadlines/raw/refs/heads/main/data"