[ main ]
plugins = [ "bilibili", "github" ,"oseddl", "invite", "hust_eat", "hust_mirror" ]
adapter = "lark"

[adapter]
app_id = "cli_a9f32aec7c39dbdc"
app_secret = "nmDh4qmzpXz45sbSoWd9WeUkBYMEx6uF"

# 供插件使用的配置
[ oseddl ]
oseddl_github_token = ""
oseddl_base_url = "https://gitee.com/YeyingXingchen/open-source-deadlines/raw/main/data"

# oseddl_base_url = "https://github.com/hust-open-atom-club/open-source-deadlines/raw/refs/heads/main/data"